# Задача 2.3. KNN

В этом задании Вам предлагается написать класс `KNN_classifier`, пригодный для решения задачи классификации (многоклассовой).

Мы предлагаем Вам шаблон класса. В этом шаблоне заполните тела функций `.fit` и `.predict`

В качестве функции близости используйте Евклидово расстояние между объектами (подробнее https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html).

Напоминание:

* Функция `.fit(x, y)` производит обучение модели. В рамках этой функции необходимо реализовать подбор оптимальных параметров модели/сконфигурировать модель для дальнейшего использования на основе данной тренировочной выборки, где x - это матрица признакового описания выборки, а y - вектор ответов.

* Функция `.predict(x)` осуществляет предсказание для каждого из объектов, чьи векторные описания представлены строками матрицы x. Выполняется строго после `.fit()`. Ради безопасности можно даже реализовать механизм отказа в виде выбрасывания специальной ошибки `UnfittedError` в случае попытки вызова функции `.predict()` до вызова функции `.fit()`.

Замечание: не изменяйте названия класса и его методов. Это приведёт к ошибке при исполнении Вашего кода в процессе проверки задания. Тем не менее, Вы можете дописать свои собственные методы, если это необходимо.

Шаблон класса:

In [ ]:
import numpy as np




class KNN_classifier:
  def __init__(self, n_neighbors: int, **kwargs):
    self.K = n_neighbors

  def fit(self, x: np.array, y: np.array):
    self.x = x
    self.y = y
    pass

  def predict(self, point: np.array):
    self.point = point
    rows, columns = self.point.shape
    classes = int(max(g for g in self.y))
    predictions = np.zeros(rows)
    points = np.concatenate((self.x, np.array([self.y]).transpose()),axis=1).tolist()

    for e in range (rows):
      keyfunc = lambda P: np.linalg.norm(P-np.append(self.point[e],P[-1]))
      sorted_points = sorted(points, key=keyfunc)
      C = np.zeros(classes+1)
      for p in sorted_points[:self.K]:
            q = int(p[-1])
            C[q] += 1

      predictions[e]= int(np.argmax(C))

    return predictions

In [ ]:
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

X,y = load_wine(return_X_y=True)
X_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
i = KNN_classifier(6)
"""
x = np.random.randint(-10,10, size= (20,4))
y = np.random.randint(0, 5, size= (20,1))
point = np.array([1,4, 2,6, 10,22, 44, 0, 1, 1, 1, 1, 1, 1, 3, 13]).reshape(-1,4)
"""
i.fit(X_train,y_train)
r = i.predict(x_test)
print(r)


o = KNeighborsClassifier(n_neighbors=6,p=2)
o.fit(X_train,y_train)
f = o.predict(x_test)
print(f)


[0. 1. 0. 1. 0. 2. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 0. 2. 1. 0.
 1. 1. 1. 0. 2. 2. 1. 0. 2. 1. 1. 1. 1. 0. 1. 2. 1. 0. 2. 0. 1.]
[0 1 0 1 0 2 1 1 0 0 1 1 1 0 1 1 1 0 1 1 0 2 1 0 1 1 1 0 2 2 1 0 2 1 1 1 1
 0 1 2 1 0 2 0 1]


In [ ]:
X,y = load_wine(return_X_y=True)
X = np.array(X)
y = np.transpose(y)
print(X.shape)
print(y.shape)
print(np.concatenate((X,y),axis=1))

(178, 13)
(178,)


ValueError: ignored

In [ ]:
import numpy as np

def euc_d(point_1_x, point_1_y, point_2_x, point_2_y):
  x_diff = point_1_x-point_2_x
  y_diff = point_1_y-point_2_y
  return np.sqrt(x_diff**2 + y_diff**2)
k = 10
point = np.array ([5, 5])

X = np.random.randint(-10,10, size= (20,2))
w = np.random.randint(0, 5, size= (20,1))
points = np.concatenate((X,w),axis=1).tolist()

keyfunc = lambda P: euc_d(P[0], P[1], point[0], point[1])
s_points = sorted(points, key=keyfunc)
print(s_points)
C = np.zeros(int(max(g[2] for g in s_points))+1)
print(C)

for p in s_points[:k]:
  q = int(p[2])
  C[q] += 1


print (C)
d = np.argmax(C)
print(f'Точка принадлежит {d} классу')


[[3, 6, 1], [5, 8, 0], [7, 2, 0], [1, 6, 0], [8, 2, 1], [1, 0, 2], [4, -3, 2], [9, -2, 2], [-3, 8, 3], [6, -4, 4], [6, -5, 4], [-5, 0, 3], [-6, 7, 4], [-6, 2, 1], [-4, -3, 0], [7, -7, 1], [-3, -7, 2], [-7, -5, 2], [-4, -8, 3], [-10, -1, 0]]
[0. 0. 0. 0. 0.]
[3. 2. 3. 1. 1.]
Точка принадлежит 0 классу


In [ ]:
point = np.array([1,4, 2,6, 10,22, 1,7, 2, 3, 2, 1]).reshape(-1,4)
x = np.random.randint(-10,10, size= (20,4))
y = np.random.randint(0, 5, size= (20,1))
K = 6
classes = int(max(g for g in y))

rows, columns = point.shape
points = np.concatenate((x, y),axis=1).tolist()

for e in range (rows):
  keyfunc = lambda P: np.linalg.norm(P-np.append(point[e], P[-1]))

  sorted_points = sorted(points, key=keyfunc)
  C = np.zeros(classes+1)
  for p in sorted_points[:K]:
        q = int(p[-1])
        C[q] += 1

  d = np.argmax(C)
  print(f'Точка принадлежит {d} классу')




Точка принадлежит 4 классу
Точка принадлежит 4 классу
Точка принадлежит 4 классу


In [ ]:
rows = 3
point = np.array([1,2, 3,4, 1,1]).reshape(-1,2)
print(point[1])
for e in range (rows):
  a= np.append (point[e], e)
  print(a)

[3 4]
[1 2 0]
[3 4 1]
[1 1 2]


## Примечания

Вы можете проверить правильность выполнения задания посредством сравнения полученных результатов с функцией из соответствующего модуля `sklearn`.

Замечание: в рамках выполнения данного задания запрещено использовать функции из пакета `sklearn` и любого другого, кроме `numpy`. Код, использующий любые другие модули не пройдёт тесты.