# 3.2 Градиентный спуск

В этом задании нам предстоит реализовать классический алгоритм градиентного спуска для обучения модели логистической регрессии.

Алгоритм выполнения этого задания следующий:

* На основе посчитанных в первом задании частных производных, напишем функцию подсчета градиента бинарной кросс-энтропии по параметрам модели

* Напишем функцию обновления весов по посчитанным градиентам

* Напишем функцию тренировки модели

Замечание:
Тренировка модели проводится в несколько циклов, в рамках каждого из которых мы обновим веса модели, основываясь на предсказании для **каждого** объекта из датасета. Такие циклы называются *эпохами*. То есть одна эпоха - это набор обновлений весов, реализованный согласно посчитанным для каждого объекта из датасета ошибкам модели.

Вам необходимо реализовать обучение модели в несколько эпох. Их количество задается параметром функции. В рамках каждой эпохи необходимо пройти циклом по всем объектам обучающей выборки и обновить веса модели.

Шаблон кода для заполнения:

In [1]:
import numpy as np
# Функция подсчета градиента
def gradient(y_true: int, y_pred: float, x: np.array) -> np.array:
  x0 = np.array([1])
  q = np.concatenate((x, x0))
  row, column = np.shape ([q])
  grad = np.zeros(column)
  for i in range (column):
    grad[i] = q[i]*((1-y_true)*y_pred - y_true*(1-y_pred))



  """
    y_true - истинное значение ответа для объекта x
    y_pred - значение степени принадлежности объекта x классу 1, предсказанное нашей моделью
    x - вектор признакового описания данного объекта

    На выходе ожидается получить вектор частных производных H по параметрам модели, предсказавшей значение y_pred
    Обратите внимание, что размерность этого градиента должна получиться на единицу больше размерности x засчет своободного коэффициента a0
  """

  pass
  return grad


# Функция обновления весов
def update(alpha: np.array, gradient: np.array, lr: float):
  row, column = np.shape ([alpha])
  alpha_new = np.zeros (column)
  for i in range(column):
    alpha_new[i] = alpha[i] - lr * gradient[i]


  """
  alpha: текущее приближения вектора параметров модели
  gradient: посчитанный градиент по параметрам модели
  lr: learning rate, множитель перед градиентом в формуле обновления параметров
  """
  return alpha_new

#функция тренировки модели
def train(alpha0: np.array, x_train: np.array, y_train: np.array, lr: float, num_epoch: int):
  """
  alpha0 - начальное приближение параметров модели
  x_train - матрица объект-признак обучающей выборки
  y_train - верные ответы для обучающей выборки
  lr - learning rate, множитель перед градиентом в формуле обновления параметров
  num_epoch - количество эпох обучения, то есть полных 'проходов' через весь датасет
  """
  row, column = np.shape(x_train)
  w = np.ones((row, 1))
  e = np.concatenate((x_train, w), axis=1) #тренировочные точки вместе с единицей на конце (чтобы был размер нужный)
  alpha = alpha0.copy()
  for epo in range(num_epoch):
    for i,x in enumerate(x_train):
      #TODO: write your code here
      y1 = np.dot(e[i], alpha)
      y = 1/(1 + np.exp(-y1))
      grad = gradient (y_train[i], y, x_train[i])
      alpha = update (alpha, grad, lr)
      pass
  return alpha

In [2]:
#масштабирование координат
def scale(X:np.array):
    x_mean = X.mean(axis=0)
    x_std  = X.std(axis=0)
    X_scaled = (X - x_mean)/x_std
    return X_scaled
class LogisticRegression(object):
  def __init__(self):
    self.alpha = None
    pass
  def fit(self, x_train, y_train, lr, num_epoch):
    self.x_train = scale(x_train)
    self.y_train = y_train
    self.lr = lr
    self.num_epoch = num_epoch

    row, column = np.shape(x_train)
    w = np.ones((row, 1))
    e = np.concatenate((self.x_train, w), axis=1) #тренировочные точки вместе с единицей на конце (чтобы был размер нужный)
    alpha = np.ones(self.x_train.shape[1]+1)
    #alpha = train(self.alpha, self.x_train, self.y_train, self.lr, self.num_epoch)
    for epo in range(num_epoch):
      for i,x in enumerate(x_train):
        y1 = np.dot(e[i], alpha)
        y = 1/(1 + np.exp(-y1))
        grad = gradient (self.y_train[i], y, self.x_train[i])
        self.alpha = update (alpha, grad, self.lr)
        pass
    return self.alpha

  def predict(self, X):
    self.X = scale(X)
    row, column = np.shape(self.X)
    ww = np.ones((row, 1))
    ee = np.concatenate((self.X, ww), axis=1)
    row, column = np.shape(self.X)
    preds = np.zeros (row+1).transpose()
    for i in range (row):
      preds[i] = 1/(1 + np.exp(-np.dot(ee[i], self.alpha)))
    return preds

In [3]:
import sklearn
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split






#Ошибка в том, что скалярное произведение очень большое по модулю. Нужно отнормировать и через пайплайн






X,y = load_wine(return_X_y=True)
X_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25)
LOL = LogisticRegression()
LOL.fit(X_train, y_train, 0.05, 8)
WWE = LOL.predict(x_test)
print(WWE)

[3.09844829e-07 7.62051195e-03 6.97138924e-01 2.21481710e-01
 9.99985037e-01 1.36042101e-01 9.35655778e-01 5.59684528e-02
 6.33432840e-01 9.97477339e-01 9.71973393e-01 9.98872386e-01
 1.89362144e-01 9.93481703e-01 7.55863033e-01 1.84327939e-01
 8.33971433e-01 9.97791576e-01 2.32546528e-01 9.99979038e-01
 9.96146275e-01 9.65127813e-01 2.01621581e-03 9.99916265e-01
 8.64615861e-01 1.19304590e-01 9.99201544e-01 5.56861593e-02
 8.65989384e-02 9.99779891e-01 3.16283519e-01 9.89986715e-01
 7.97692406e-02 2.11536801e-02 2.59822342e-01 7.31201159e-03
 3.71580028e-01 3.30720976e-02 1.54607624e-01 9.73356458e-01
 9.99434914e-01 7.18422455e-01 9.97572523e-01 2.58922039e-02
 2.16513153e-03 0.00000000e+00]


# Замечание:

В случае, если у Вас возникли сложности с выполнением первого задания и, как следствие, у Вас не выходит сделать это, мы рекомендуем подробно ознакомиться с главой **Производные $\frac{\partial H}{\partial \omega_i}$** нашей [лекции](https://colab.research.google.com/drive/1xjX_YnXcRr8HSiYLByMHxEIAADqs7QES?usp=sharing)

In [ ]:
import numpy as np
x1 = np.array([[10, 5], [0, 4]])
x2 = np.ones((2,1))
row, column = np.shape(x1)
print(x1)
w = np.ones((row,1))
print(w)
r = np.concatenate((x1, w), axis =1)
print(r)

[[10  5]
 [ 0  4]]
[[1.]
 [1.]]
[[10.  5.  1.]
 [ 0.  4.  1.]]


In [ ]:
c = np.array([4, 9])
v = np.array([3, 2])
t = np.dot(c, v)
print(t)

30
